[package]
name = "rtxt_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
colored = "3.0.0"
glob = "0.3.3"
serde_json = "1.0.145"
serde_yaml = "0.9.34"
toml = "0.9.8"
[dependencies.clap]
version = "4.5.49"
features = ["derive"]